### ISSUE TITLE
CS-202 Fix/ArgoCD 오류

### ISSUE THREAD

**Issue by Kim-Yukyung** [KEA-ChunSam/PlayUs-k8s#13]
### 상위 작업 (Epic, 보라색 번개) Ticket Number

CS-22

### 이슈 내용 (Description)

overlays/develop/user-service/.env.secret 파일이 Git에 없어서 ArgoCD → kustomize 실행 실패

### 담당자 이름

김유

### 상세 내용 (Details)

kustomization.yaml에서
```
secretGenerator:
  - name: user-db-secret
    envs:
      - .env.secret
  ```
이렇게 .env.secret 파일을 불러오려고 했는데, ArgoCD가 Git에서 소스를 내려받았을 때 이 파일이 없어 오류 발생
일단 dummy data로 임시 해결을 하고, ArgoCD 구축 후에 sealed-secrets (Bitnami)를 통해 암호화로 해결하겠습니다

### 체크리스트 (Tasks)

- [ ] Tasks1
- [ ] Tasks2

### 참조 (References)

- Reference1
